<a href="https://colab.research.google.com/github/profteachkids/CHE2064/blob/master/RadauLobatto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [132]:
import numpy as np
from plotly.subplots import make_subplots
from scipy.optimize import root

In [65]:
def radau(N):
    x=np.zeros(N)
    w=np.zeros(N)
    x[0]=-1
    w[0]=2/N**2
    x[1:]=((np.polynomial.Legendre.basis(N-1)+np.polynomial.Legendre.basis(N))//np.polynomial.Polynomial([1,1]).convert(kind=np.polynomial.Legendre)).roots()
    w[1:]=(1-x[1:])/(N*np.polynomial.Legendre.basis(N-1)(x[1:]))**2
    return x,w

In [82]:
def lobatto(N):
    x=np.zeros(N)
    w=np.zeros(N)
    x[0]=-1
    x[-1]=1
    w[0]=w[-1]=2/N/(N-1)
    x[1:-1]=(np.polynomial.Legendre.basis(N-1).deriv()).roots()
    w[1:-1]=2/N/(N-1)/(np.polynomial.Legendre.basis(N-1)(x[1:-1]))**2
    return x,w


In [174]:
def eqs(v,x):
    Y=np.polynomial.Chebyshev(v,domain=(0,5))
    return np.concatenate([np.array([Y(0)-2, Y.deriv()(0)-1.]), (Y.deriv(2)+4*Y)(x)])

In [175]:
x,w=np.polynomial.legendre.leggauss(10)
x=(x+1)*5/2

In [176]:
v0=np.ones(12)

In [177]:
eqs(v0,x)

array([  -2.        ,   25.4       , -213.38330803,   43.56828108,
        -17.17024866,   14.30119535,   -7.82621438,   11.49481199,
         -8.99803055,   17.8070633 ,  -38.81606381, 1284.33469154])

In [178]:
sol=root(lambda v: eqs(v,x),v0)

In [179]:
sol

 message: The solution converged.
 success: True
  status: 1
     fun: [-2.220e-16  8.882e-16 -5.482e-15 -2.580e-15 -1.535e-16
            6.228e-16  2.849e-16 -1.966e-16 -5.961e-16 -6.592e-17
            2.736e-15  5.829e-15]
       x: [-1.561e-02 -1.349e+00 -8.187e-03 -1.503e+00  6.877e-02
            1.076e+00 -2.304e-02 -2.200e-01  3.224e-03  2.290e-02
           -2.324e-04 -1.424e-03]
    nfev: 16
    fjac: [[-7.881e-02 -2.098e-09 ... -3.152e-01 -3.152e-01]
           [ 1.133e-01 -4.560e-02 ... -3.973e-01 -4.469e-01]
           ...
           [-6.252e-02  1.061e-01 ... -2.557e-01  8.037e-02]
           [ 6.234e-02  9.219e-03 ...  1.301e-01 -3.699e-02]]
       r: [-1.269e+01  7.881e-02 ... -3.872e-01 -9.399e+01]
     qtf: [-5.687e-11  1.463e-10 -5.494e-11  7.895e-11  6.890e-11
            1.941e-11  1.209e-10 -4.998e-11 -5.691e-11 -1.533e-11
            3.843e-11 -1.239e-12]

In [181]:
xplot=np.linspace(0,5,100)
fig=make_subplots()
Y=np.polynomial.Chebyshev(sol.x,domain=(0,5))
fig.add_scatter(x=xplot,y=Y(xplot),mode='markers')
fig.add_scatter(x=xplot,y=(np.sin(2*xplot)+4*np.cos(2*xplot))/2,mode='lines')